/**
 * generated by Xtext
 */
package org.xtext.htwg.seapal.validation;

import org.xtext.htwg.seapal.validation.AbstractWaypointValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class WaypointValidator extends AbstractWaypointValidator {
}
