/*
 * generated by Xtext
 */
package org.xtext.htwg.seapal.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.htwg.seapal.ui.internal.WaypointActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WaypointExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return WaypointActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return WaypointActivator.getInstance().getInjector(WaypointActivator.ORG_XTEXT_HTWG_SEAPAL_WAYPOINT);
	}
	
}
