/*
* generated by Xtext
*/
package org.xtext.htwg.seapal.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class WaypointAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/xtext/htwg/seapal/parser/antlr/internal/InternalWaypoint.tokens");
	}
}
