/**
 * generated by Xtext
 */
package org.xtext.htwg.seapal.ui.contentassist;

import org.xtext.htwg.seapal.ui.contentassist.AbstractWaypointProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class WaypointProposalProvider extends AbstractWaypointProposalProvider {
}
