/*
 * generated by Xtext
 */
package org.xtext.htwg.seapal.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class WaypointUiModule extends org.xtext.htwg.seapal.ui.AbstractWaypointUiModule {
	public WaypointUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
