<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="waypoint" nsURI="http://www.xtext.org/htwg/seapal/Waypoint"
    nsPrefix="waypoint">
  <eClassifiers xsi:type="ecore:EClass" name="Waypoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="waypoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="btm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dtm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cog" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sog" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maneuver" eType="#//Maneuver"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="foresail" eType="#//Foresail"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mainsail" eType="#//Mainsail"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Maneuver">
    <eLiterals name="NONE" literal="none"/>
    <eLiterals name="TACK" value="1" literal="Tack"/>
    <eLiterals name="JIBE" value="2" literal="Jibe"/>
    <eLiterals name="LAYTO" value="3" literal="Layto"/>
    <eLiterals name="SETSAILS" value="4" literal="Set Sails"/>
    <eLiterals name="CHANGESAILS" value="5" literal="Change Sails"/>
    <eLiterals name="SAILSDOWN" value="6" literal="Sails Down"/>
    <eLiterals name="REFF" value="7" literal="Reff"/>
    <eLiterals name="ANKERUP" value="8" literal="Anker Up"/>
    <eLiterals name="ANKERDOWN" value="9" literal="Anker Down"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Foresail">
    <eLiterals name="NONE" literal="none"/>
    <eLiterals name="GENUA1" value="1" literal="Genua1"/>
    <eLiterals name="GENUA2" value="2" literal="Genua2"/>
    <eLiterals name="GENUA3" value="3" literal="Genua3"/>
    <eLiterals name="FOCK" value="4" literal="Fock"/>
    <eLiterals name="STORMFOCK" value="5" literal="Storm Fock"/>
    <eLiterals name="BISTER" value="6" literal="Bister"/>
    <eLiterals name="SPINACKER" value="7" literal="Spinacker"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Mainsail">
    <eLiterals name="NONE" literal="none"/>
    <eLiterals name="FULL" value="1" literal="full"/>
    <eLiterals name="REEF1" value="2" literal="Reef1"/>
    <eLiterals name="REEF2" value="3" literal="Reef2"/>
  </eClassifiers>
</ecore:EPackage>
