/*
* generated by Xtext
*/
package org.xtext.htwg.seapal.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.htwg.seapal.services.WaypointGrammarAccess;

public class WaypointParser extends AbstractContentAssistParser {
	
	@Inject
	private WaypointGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.htwg.seapal.ui.contentassist.antlr.internal.InternalWaypointParser createParser() {
		org.xtext.htwg.seapal.ui.contentassist.antlr.internal.InternalWaypointParser result = new org.xtext.htwg.seapal.ui.contentassist.antlr.internal.InternalWaypointParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getManeuverAccess().getAlternatives(), "rule__Maneuver__Alternatives");
					put(grammarAccess.getForesailAccess().getAlternatives(), "rule__Foresail__Alternatives");
					put(grammarAccess.getMainsailAccess().getAlternatives(), "rule__Mainsail__Alternatives");
					put(grammarAccess.getWaypointAccess().getGroup(), "rule__Waypoint__Group__0");
					put(grammarAccess.getWaypointAccess().getWaypointAssignment_1(), "rule__Waypoint__WaypointAssignment_1");
					put(grammarAccess.getWaypointAccess().getPositionAssignment_2(), "rule__Waypoint__PositionAssignment_2");
					put(grammarAccess.getWaypointAccess().getNoteAssignment_3(), "rule__Waypoint__NoteAssignment_3");
					put(grammarAccess.getWaypointAccess().getBtmAssignment_4(), "rule__Waypoint__BtmAssignment_4");
					put(grammarAccess.getWaypointAccess().getDtmAssignment_5(), "rule__Waypoint__DtmAssignment_5");
					put(grammarAccess.getWaypointAccess().getCogAssignment_6(), "rule__Waypoint__CogAssignment_6");
					put(grammarAccess.getWaypointAccess().getSogAssignment_7(), "rule__Waypoint__SogAssignment_7");
					put(grammarAccess.getWaypointAccess().getManeuverAssignment_8(), "rule__Waypoint__ManeuverAssignment_8");
					put(grammarAccess.getWaypointAccess().getForesailAssignment_9(), "rule__Waypoint__ForesailAssignment_9");
					put(grammarAccess.getWaypointAccess().getMainsailAssignment_10(), "rule__Waypoint__MainsailAssignment_10");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.htwg.seapal.ui.contentassist.antlr.internal.InternalWaypointParser typedParser = (org.xtext.htwg.seapal.ui.contentassist.antlr.internal.InternalWaypointParser) parser;
			typedParser.entryRuleWaypoint();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public WaypointGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(WaypointGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
