/*
 * generated by Xtext
 */
package org.xtext.htwg.seapal;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WaypointRuntimeModule extends org.xtext.htwg.seapal.AbstractWaypointRuntimeModule {

}
