/*
* generated by Xtext
*/
package org.xtext.htwg.seapal;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class WaypointStandaloneSetup extends WaypointStandaloneSetupGenerated{

	public static void doSetup() {
		new WaypointStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

